-- ===========================================================
-- Project: Restaurant Operations Intelligence Platform
-- Author: Rahmath Mozumder
-- Description: Creates all database tables
-- Database: PostgreSQL
-- ===========================================================


CREATE TABLE branches (
    branch_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    branch_name VARCHAR(100) NOT NULL,
    city VARCHAR(50) NOT NULL,
    address VARCHAR(200) NOT NULL,
    opening_date DATE NOT NULL,
    seating_capacity INTEGER,
    opening_time TIME,
    closing_time TIME,
    manager_name VARCHAR(100),
    phone_number VARCHAR(20),
    status VARCHAR(20) NOT NULL
);


CREATE TABLE products (
    product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(20) NOT NULL UNIQUE,
    product_name VARCHAR(100) NOT NULL,
    category VARCHAR(50) NOT NULL,
    product_size VARCHAR(20),
    selling_price DECIMAL(10,2) NOT NULL,
    food_cost DECIMAL(10,2) NOT NULL,
    preparation_time INTEGER,
    calories INTEGER,
    menu_status VARCHAR(20) NOT NULL,
    supplier VARCHAR(100),
    created_date DATE NOT NULL,
    subcategory VARCHAR(50) NOT NULL,
    serving_temperature VARCHAR(10) NOT NULL,
);


CREATE TABLE orders (
    order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id INTEGER NOT NULL,
    order_date DATE NOT NULL,
    order_time TIME NOT NULL,
    order_channel VARCHAR(20) NOT NULL,
    customer_count INTEGER,
    discount_amount DECIMAL(10,2) DEFAULT 0,
    final_amount DECIMAL(10,2) NOT NULL,
    order_status VARCHAR(20) NOT NULL,
    table_number INTEGER NOT NULL,
    CONSTRAINT fk_orders_branch
        FOREIGN KEY (branch_id)
        REFERENCES branches(branch_id)
);


CREATE TABLE order_items (
    order_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,
    line_total DECIMAL(10,2) NOT NULL,
    item_status VARCHAR(20) NOT NULL,

    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id),

    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id)
);

CREATE TABLE employees (
    employee_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id INTEGER NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    job_role VARCHAR(50) NOT NULL,
    hire_date DATE NOT NULL,
    hourly_rate DECIMAL(6,2) NOT NULL,
    employment_type VARCHAR(20) NOT NULL,
    email VARCHAR(100) UNIQUE,
    employment_status VARCHAR(20) NOT NULL,

    CONSTRAINT fk_employees_branch
        FOREIGN KEY (branch_id)
        REFERENCES branches(branch_id)
    CONSTRAINT chk_employees_job_role CHECK (
    job_role IN (
        'General Manager',
        'Assistant Manager FOH',
        'Assistant Manager BOH',
        'Head Chef',
        'Team Leader FOH',
        'Team Leader BOH',
        'Kitchen Team Member',
        'Front of House Team Member',
        'Kitchen Porter'
    )
)
);

CREATE TABLE shifts (
    shift_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL,
    branch_id INTEGER NOT NULL,
    shift_date DATE NOT NULL,
    shift_start TIME NOT NULL,
    shift_end TIME NOT NULL,
    hours_worked DECIMAL(5,2),
    shift_type VARCHAR(20),
    overtime_hours DECIMAL(5,2) DEFAULT 0,
    shift_status VARCHAR(20) NOT NULL,
    work_area VARCHAR(20) NOT NULL,

    CONSTRAINT fk_shifts_employee
        FOREIGN KEY (employee_id)
        REFERENCES employees(employee_id),

    CONSTRAINT fk_shifts_branch
        FOREIGN KEY (branch_id)
        REFERENCES branches(branch_id)
);

CREATE TABLE payments (
    payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL,
    payment_method VARCHAR(20) NOT NULL,
    payment_amount DECIMAL(10,2) NOT NULL,
    payment_date DATE NOT NULL,
    payment_time TIME NOT NULL,
    payment_status VARCHAR(20) NOT NULL,
    transaction_reference VARCHAR(100) UNIQUE,

    CONSTRAINT fk_payments_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id)
);


CREATE TABLE waste_records (
    waste_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    employee_id INTEGER,
    order_item_id INTEGER,
    waste_date DATE NOT NULL,
    waste_time TIME NOT NULL,
    quantity INTEGER NOT NULL,
    wasted_portion_size VARCHAR(20),
    waste_reason VARCHAR(50) NOT NULL,
    estimated_cost DECIMAL(10,2),
    notes TEXT,

    CONSTRAINT fk_waste_branch
        FOREIGN KEY (branch_id)
        REFERENCES branches(branch_id),

    CONSTRAINT fk_waste_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id),

    CONSTRAINT fk_waste_employee
        FOREIGN KEY (employee_id)
        REFERENCES employees(employee_id)
);


CREATE TABLE customer_feedback (
    feedback_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL UNIQUE,
    branch_id INTEGER NOT NULL,
    feedback_date DATE NOT NULL,
    overall_rating INTEGER,
    food_rating INTEGER,
    service_rating INTEGER,
    cleanliness_rating INTEGER,
    would_recommend BOOLEAN,
    complaint_category VARCHAR(50),
    feedback_comment TEXT,

    CONSTRAINT fk_feedback_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id),

    CONSTRAINT fk_feedback_branch
        FOREIGN KEY (branch_id)
        REFERENCES branches(branch_id)
);

CREATE TABLE service_metrics (
    service_metric_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL UNIQUE,
    branch_id INTEGER NOT NULL,
    order_received_time TIME NOT NULL,
    kitchen_start_time TIME,
    food_ready_time TIME,
    order_served_time TIME,
    service_status VARCHAR(20) NOT NULL,
    delay_reason VARCHAR(100),

    CONSTRAINT fk_service_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id),

    CONSTRAINT fk_service_branch
        FOREIGN KEY (branch_id)
        REFERENCES branches(branch_id)
);