CREATE TABLE "branches" (
  "branch_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "branch_name" varchar NOT NULL,
  "city" varchar NOT NULL,
  "address" varchar NOT NULL,
  "opening_date" date NOT NULL,
  "seating_capacity" int,
  "opening_time" time,
  "closing_time" time,
  "manager_name" varchar,
  "phone_number" varchar,
  "status" varchar NOT NULL
);

CREATE TABLE "products" (
  "product_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sku" varchar UNIQUE NOT NULL,
  "product_name" varchar NOT NULL,
  "category" varchar NOT NULL,
  "product_size" varchar,
  "selling_price" decimal(10,2) NOT NULL,
  "food_cost" decimal(10,2) NOT NULL,
  "preparation_time" int,
  "calories" int,
  "menu_status" varchar NOT NULL,
  "supplier" varchar,
  "created_date" date NOT NULL
);

CREATE TABLE "orders" (
  "order_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "branch_id" int NOT NULL,
  "order_date" date NOT NULL,
  "order_time" time NOT NULL,
  "order_channel" varchar NOT NULL,
  "customer_count" int,
  "discount_amount" decimal(10,2) DEFAULT 0,
  "final_amount" decimal(10,2) NOT NULL,
  "order_status" varchar NOT NULL
);

CREATE TABLE "order_items" (
  "order_item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int NOT NULL,
  "product_id" int NOT NULL,
  "quantity" int NOT NULL,
  "unit_price" decimal(10,2) NOT NULL,
  "line_total" decimal(10,2) NOT NULL
);

CREATE TABLE "employees" (
  "employee_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "branch_id" int NOT NULL,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "job_role" varchar NOT NULL,
  "hire_date" date NOT NULL,
  "hourly_rate" decimal(10,2) NOT NULL,
  "employment_type" varchar NOT NULL,
  "email" varchar UNIQUE,
  "employment_status" varchar NOT NULL
);

CREATE TABLE "shifts" (
  "shift_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" int NOT NULL,
  "branch_id" int NOT NULL,
  "shift_date" date NOT NULL,
  "shift_start" time NOT NULL,
  "shift_end" time NOT NULL,
  "hours_worked" decimal(5,2),
  "shift_type" varchar,
  "overtime_hours" decimal(5,2) DEFAULT 0,
  "shift_status" varchar NOT NULL
);

CREATE TABLE "payments" (
  "payment_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int NOT NULL,
  "payment_method" varchar NOT NULL,
  "payment_amount" decimal(10,2) NOT NULL,
  "payment_date" date NOT NULL,
  "payment_time" time NOT NULL,
  "payment_status" varchar NOT NULL,
  "transaction_reference" varchar UNIQUE
);

CREATE TABLE "waste_records" (
  "waste_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "branch_id" int NOT NULL,
  "product_id" int NOT NULL,
  "employee_id" int,
  "waste_date" date NOT NULL,
  "waste_time" time NOT NULL,
  "quantity" int NOT NULL,
  "wasted_portion_size" varchar,
  "waste_reason" varchar NOT NULL,
  "estimated_cost" decimal(10,2),
  "notes" varchar
);

CREATE TABLE "customer_feedback" (
  "feedback_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int UNIQUE NOT NULL,
  "branch_id" int NOT NULL,
  "feedback_date" date NOT NULL,
  "overall_rating" int,
  "food_rating" int,
  "service_rating" int,
  "cleanliness_rating" int,
  "would_recommend" boolean,
  "complaint_category" varchar,
  "feedback_comment" varchar
);

CREATE TABLE "service_metrics" (
  "service_metric_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int UNIQUE NOT NULL,
  "branch_id" int NOT NULL,
  "order_received_time" time NOT NULL,
  "kitchen_start_time" time,
  "food_ready_time" time,
  "order_served_time" time,
  "service_status" varchar NOT NULL,
  "delay_reason" varchar
);

ALTER TABLE "orders" ADD FOREIGN KEY ("branch_id") REFERENCES "branches" ("branch_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "employees" ADD FOREIGN KEY ("branch_id") REFERENCES "branches" ("branch_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "shifts" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "shifts" ADD FOREIGN KEY ("branch_id") REFERENCES "branches" ("branch_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payments" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "waste_records" ADD FOREIGN KEY ("branch_id") REFERENCES "branches" ("branch_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "waste_records" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "waste_records" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "customer_feedback" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "customer_feedback" ADD FOREIGN KEY ("branch_id") REFERENCES "branches" ("branch_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "service_metrics" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "service_metrics" ADD FOREIGN KEY ("branch_id") REFERENCES "branches" ("branch_id") DEFERRABLE INITIALLY IMMEDIATE;
